### ISSUE TITLE
TODO Homepage

### ISSUE THREAD

**Issue by marineb** [nypublicradio/wqxr-web-client#11]
- [x] Make whole story clickable
- [x] Fix old styles
- [x] Live stream Launch pad layout
- [x] Ad fake ad

Pre-Brian:
- [x] Update styles for livestream player
- [x] Hover state on stories

With Brian:
- [x] What happens when less stories -- min of 8 stories, above, card layout
- [x] Add listen buttons
- [x] Mobile live stream player vs desktop -- what do we do with this code

Post Brian:
- [x]  Continue with code review stuff I didn't do
- [x] row has ad / doesn't 
- [x] Player ticket - meta data when show has playlist, when it doesn't
