### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marineb** [nypublicradio/wqxr-web-client#58]
- [x] mobile scroll causes the tap to trigger, fix that so tap state only appears on tap
- [x] story desktop body too wide
- [x] story mobile leave same size as desktop
